version: "2"

services:
  # fileinfo:
  #   build: .
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   networks:
  #     - malice
  db:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "8081:8080"
    volumes:
      - ~/.malice/db:/data
    networks:
      - malice

networks:
  malice:
    driver: bridge
